[project]
name = "330-1-bachelor-thesis"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "altair>=6.1.0",
    "fastparquet>=2026.5.0",
    "ipython>=9.13.0",
    "matplotlib>=3.10.9",
    "numpy>=2.4.6",
    "pandas>=3.0.3",
    "polars>=1.41.0",
    "pyarrow>=24.0.0",
    "scipy>=1.17.1",
    "tqdm>=4.67.3",
    "tsfel>=0.2.0",
    "tsfresh>=0.21.2",
]
